### ISSUE TITLE
Separate the domain model and persistence layer

### ISSUE THREAD

**Issue by mohammadhsn** [simara-svatopluk/cart#13]
Hi
Thanks for your great blog post and its repository. 

I have a design-related question, As I know about **DDD** and some sources I read, most people indicate separations between domain and persistence (or infrastructure in general). Most people use Doctrine ORM when they consider the DDD approach in PHP, domain models (or Entities) are a **part of domain** just like what you did in the source code, the question is here:
[Cart](https://github.com/simara-svatopluk/cart/blob/master/src/Domain/Cart/Cart.php#L19) is a **domain concern** and it has no idea about persistence/infrastructure, but we see doctrine mapping annotations in the domain model to mapping Entity to RDBMS relationships. Is there any way you know to separate doctrine's stuff (Entity) and the domain model?
In my case, I wanna declare [items](https://github.com/simara-svatopluk/cart/blob/master/src/Domain/Cart/Cart.php#L15) as `pure PHP array` instead Doctrine `ArrayCollection` class.

**Comment by simara-svatopluk** [comment]
Hi,
that's great You find blog posts and this repository helpful, and thanks for Your question.

Longer answer that `ArrayCollection` might be a viable option: https://svatasimara.medium.com/absolutely-3da04ff55c3c

But back to Your actual question
> Is there any way you know to separate doctrine's stuff (Entity) and the domain model?

If You want to have data stored in separated tables, then no, I don't know such option.

But if You accept that collection doesn't have to be stored in separated table, then it can be stored in a JSON field (or document by some sources) by custom type.
* Relational databases are good in dealing with JSON documents today
* Migration of data is possible
* I've even written an article about this solution :-D https://svatasimara.medium.com/domain-driven-design-part-7-alternative-relational-database-mapping-9ddc419685c8
  * The article describes custom value object, but it can be used for array of objects as well

**Comment by mohammadhsn** [comment]
Great,
Thanks for the answer.

**Comment by simara-svatopluk** [comment]
You are welcome, and I do thank You for the question.

If You have more topics, or You find a new interesting way to solve the issue above, just write me.
I like discussions, different angles of view... Even this question stressed my knowledge of persistence again, and I had to think about the answer. And I love thinking :-)
